all: project-proposal.pdf
	mv project-proposal.pdf EECS395.Spring2013.Cherukuri.Dooner.Little.Stack.Proposal.Project.October.pdf
project-proposal.pdf: project-proposal.tex db_diagram.pdf
	pdflatex project-proposal.tex
